# Generated by Django 4.1.1 on 2022-09-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MP_files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_file', models.FileField(upload_to='files')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Uploaded_Data',
            },
        ),
    ]
